### ISSUE TITLE
Redirection URL doesn't work

### ISSUE THREAD

**Issue by waseem-h** [keycloak/keycloak-gatekeeper#331] opened 2018-03-20 08:16 UTC
Hi, i've been using your keycloak-proxy for a while now and i'm facing a minor issue. Basically I have your proxy running as a sidecar container with an app on kubernetes. The issue is that the app itself is on someurl.com/app and whenever i visit the url, it takes me to keycloak, but the redirect_url in the browser url shows "'someurl.com" instead of someurl.com/app. So after logging in I am redirected to someurl.com which is weird

i've tried passing the argument `redirection-url=/app` but it doesn't work as well. Here's my config

```yaml
client-id: <client-id>
client-secret: <client-secret>
discovery-url: https://<keycloak-url>/auth/realms/<realm>
enable-default-deny: true
listen: 0.0.0.0:80
upstream-url: http://127.0.0.1:5601
redirection-url: /kibana
secure-cookie: false
verbose: true
enable-logging: true
cors-origins:
- '*'
cors-methods:
- GET
- POST
resources:
- uri: /

```

**Comment by gambol99** [comment] 2018-03-21 23:35
hi @waseem-h ... the redirection-url should the full url of the site ... i.e. https://example.com .. Assuming the redirection-url is not [provided it will use the Host header](https://github.com/gambol99/keycloak-proxy/blob/master/handlers.go#L39-L59)

**Comment by Josh-West-Bose** [comment] 2018-03-23 19:47
I'm running into this issue as well unfortunately, even with a fully qualified redirection URL.

I get sent to https://<host>/oauth/callback instead of https://<host>/<stuff>/oauth/authorize?...

**Comment by waseem-h** [comment] 2018-04-03 07:24
@gambol99 i tried with full url but still it doesn't seem to work

**Comment by dlohin** [comment] 2018-06-22 13:13
I am somewhat seeing a similiar issue with Kibana in a sidecar.  When I got to the URL, I am redirected to Keycloak (good) I logon and then I get sent to oauth/callback (as documented) but I am given access denied.

When I look at the Keycloak Proxy logs I see: 1.5296725145237534e+09	error	unable to exchange code for access token	{"error": "invalid_grant: Code not valid"}

After I have authenticated, though I can erase the oauth/callback uri and then hit enter again and it goes through fine.  Admittedly I don't entirely know what I am doing here, but is the oauth callback stripped by the proxy or does that make it back to the web service?  I am assuming I have some errors somwhere.

        args:
          - --listen=0.0.0.0:8080
          - --discovery-url=https://keycloak.local/auth/realms/edcop
          - --client-id=kibana
          - --client-secret=<removed>
          - --enable-refresh-tokens=true
          - --encryption-key=<removed>  # 32 bytes string
          - --redirection-url=https://kibana.local/
          - --upstream-url=http://127.0.0.1:5601/app/kibana/
          - --resources=uri=/*

**Comment by s-yagodkin** [comment] 2018-07-02 07:39
I've got the same issue with Ingress, it always redirects back to root url instead of redirection url. Is there any workaround?

**Comment by codepainters** [comment] 2018-07-06 15:46
I tried `keycloak-proxy` today, just to encounter the very same problem.

As far as I can follow the code, the root cause: the very same value ``r.config.OAuthURI``  is used for both route configuration, as well as for redirects.

The part where route is set: https://github.com/gambol99/keycloak-proxy/blob/7eb239265bce724c1400c2945cbf784663729748/server.go#L193-L195

Here's the code that constructs self-addressed URIs: https://github.com/gambol99/keycloak-proxy/blob/7eb239265bce724c1400c2945cbf784663729748/config.go#L62-L65

And here's one of the usages: https://github.com/gambol99/keycloak-proxy/blob/7eb239265bce724c1400c2945cbf784663729748/misc.go#L107-L111

As a result, e.g.:
- if you set `--oauth-uri=/oauth` (default)  - redirect will not work (it will redirect to `/oauth/....`)
- if you set `--oauth-uri=/kibana/oauth` - redirect will work, but routing will not (which leads to redirect loop)

**Comment by codepainters** [comment] 2018-07-06 21:57
I've tried a workaround - as I have bare NginX running in front of `keycloak-proxy` and `kubernetes-dashboard`. Namely, I handle `/dashboard/oauth/...` and other `/dashboard/...` URIs differently:

```
 # request to the proxy OAuth endpoints - leave URL as is (preserve /dashboard/ prefix)
 location ~ ^(/dashboard/oauth/.*)$ {
    ...
    proxy_pass  http://127.0.0.1:31480/$1$is_args$args;
    ...
  }

  # requests to actual dashboard - strip away the /dashboard/ prefix
  location ~ ^/dashboard/(.*)$ {
    # ...
    proxy_pass  http://127.0.0.1:31480/$1$is_args$args;
    # ...
  }
```

The proxy itself is running with `--oauth-uri=/dashboard/oauth` option. 

This sort of works, with one gotcha - the last redirect performed by `/oauth/callback` endpoint goes to `/`, instead of `/dashboard`. It is possible to manually enter the right URI and dashboard loads properly.  

This is because the first redirect from `/dashboard/` to `/dashboard/oauth/authorize` sees `/` as the URI and that's what it encodes into `state` URI parameter. I've no idea yet how to work this issue around. 

I believe proper fix requires extending `keycloak-proxy` configuration with `MountUri` parameter (or whatever it's called), which gets prepended to all generated redirect URIs.

**Comment by abstractj** [comment] 2018-10-01 14:04
@waseem-h I'm closing this for now, as it seems to be addressed on @codepainters' PR. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.

**Closed by abstractj** 2018-10-01 14:04 UTC
