### ISSUE TITLE
"invalid client secret" issue v2.1.1, using proxy

### ISSUE THREAD

**Issue by jxhcapgemini** [keycloak/keycloak-gatekeeper#356] opened 2018-05-09 15:43 UTC
Struggling with why keycloak proxy is returning this error: 

`{"level":"info","ts":1525879825.1931584,"caller":"keycloak-proxy/middleware.go:71","msg":"client request","latency":0.000100659,"status":307,"bytes":317,"client_ip":"127.0.0.1:48554","method":"GET","path":"/oauth/authorize"}
{"level":"error","ts":1525879861.8614936,"caller":"keycloak-proxy/handlers.go:120","msg":"unable to exchange code for access token","error":"unauthorized_client: Invalid client secret"}
{"level":"info","ts":1525879861.8615599,"caller":"keycloak-proxy/middleware.go:71","msg":"client request","latency":0.030128956,"status":403,"bytes":0,"client_ip":"127.0.0.1:48768","method":"GET","path":"/oauth/callback"}`

we've set the`--openid-provider-proxy` parameter... and the redirect url is not a public domain (i.e. we're implementing this in a dev environment). 

Any idea what might be going on here? Could this be the outbound proxy failing? We've tried explicitly passing in the client secret -- it returns the same error.

**Comment by jangaraj** [comment] 2018-05-09 15:58
What kind of Identity Provider are you using? I have a problem with some specific IdP, because of https://github.com/gambol99/go-oidc/pull/4

**Comment by jxhcapgemini** [comment] 2018-05-09 16:11
@jangaraj I'm not sure as the developer who has server access is not in until tomorrow - however it's a corporate, so I assume it's an internal IdP..

What was your fix?

**Comment by jangaraj** [comment] 2018-05-09 16:26
One line fix https://github.com/gambol99/go-oidc/pull/4/files - you will need to patch keycloak-proxy code: 
```
find . -type f -exec sed -i 's#github.com/gambol99/go-oidc#github.com/jangaraj/go-oidc#g' {} +
```
and build your own keycloak-proxy version. 

Your case can be different. Maybe you really don't have correct client secret in configuration. Also, non ASCI characters in the client id/secret can be a problem for some IdP.

**Comment by fkpwolf** [comment] 2018-07-24 03:01
I came across this issue and found root cause is "--client-secret" parameter value was wrong. To fix it, copy value from keycloak admin page.

**Comment by abstractj** [comment] 2018-10-01 14:14
@jxhcapgemini I'm closing this as it seems to be an usability issue. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.

**Closed by abstractj** 2018-10-01 14:14 UTC
